{% set name = "arabic_reshaper" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a236fc6e9dde2a61cc6a5ca962b522e42694e1bb2a2d86894ed7a4eba4ce1890

build:
  noarch: python
  number: 0
  # Note: --no-deps is currently required due to https://github.com/conda/conda-build/issues/3254
  # Once resolved, it should be removed.
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - configparser
    - future

test:
  imports:
    - arabic_reshaper

about:
  home: https://github.com/mpcabd/python-arabic-reshaper
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Reconstruct Arabic sentences to be used in applications that don't support Arabic

extra:
  recipe-maintainers:
    - hoechenberger
    - kastman
