{% set name = "arabic_reshaper" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a0d9b2a9fa29b5f2c1d705f407adf6ca4242405b9cac0e5cc09e6c4f3f8fb68c

build:
  noarch: python
  number: 0
  # Note: --no-deps is currently required due to https://github.com/conda/conda-build/issues/3254
  # Once resolved, it should be removed.
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - hatchling
  run:
    - python >={{ python_min }}
    - setuptools
    - configparser
    - future

test:
  requires:
    - python {{ python_min }}
  imports:
    - arabic_reshaper

about:
  home: https://github.com/mpcabd/python-arabic-reshaper
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Reconstruct Arabic sentences to be used in applications that don't support Arabic

extra:
  recipe-maintainers:
    - hoechenberger
    - kastman
    - mrakitin
